project:
  type: website
  output-dir: _site

website:
  title: "Martina Pardy"
  navbar:
    left:
      - href: "#home"
        text: Home
      - href: "#about"
        text: About
      - href: "#grants"
        text: Grants & Funding
      - href: "#research"
        text: Research
      - href: "#training-events"
        text: Training & Events
      - href: "#contact"
        text: Contact

format:
  html:
    theme: cosmo
    toc: true
