project:
  type: website
  output-dir: _site

website:
  title: "Martina Pardy"
  navbar:
    left:
      - href: index.md
        text: Home
      - href: about.md
        text: About
      - href: research.md
        text: Research
      - href: events.md
        text: Training & Events
      - href: contact.md
        text: Contact

format:
  html:
    theme: cosmo
    toc: true
